/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateEmotion */

#ifndef _Included_CreateEmotion
#define _Included_CreateEmotion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CreateEmotion
 * Method:    captureCommons
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_captureCommons
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    captureDisgusts
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_captureDisgusts
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    captureHappys
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_captureHappys
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    resize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_resize
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    createXml
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_createXml
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    createSVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_createSVM
  (JNIEnv *, jobject);

/*
 * Class:     CreateEmotion
 * Method:    predictEmotion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CreateEmotion_predictEmotion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
